link = 'https://docs.google.com/forms/d/e/1FAIpQLSe49i8NIJRYzuDeZbc6bDMC9XL_oV-dx2UlxhydnbrfkVFUpA/viewform' #Enter Form Link Here
email = '' #Enter Your ADYPU email id Here
passwd = '' #Enter Your ADYPU email id Password Here
name='' #Enter Your Full Name Here
urn='' #Enter Your URN Here
cmnt1='' #Enter comment for page 1
cmnt2='' #Enter comment for page 2
cmnt3='' #Enter comment for page 3
cmnt4='' #Enter comment for page 4
cmnt5='' #Enter comment for page 5
cmnt6='' #Enter comment for page 6
cmnt7='' #Enter comment for page 7